ktor:
  application:
    modules:
      - com.kvartalica.ApplicationKt.module
  deployment:
    port: 8080
    host: localhost
  development: true
admin:
  email: "admin@"
  password: "admin_password"
jwt:
  domain: "http://localhost:8080/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost:5432/kvartalica"
  user: postgres
  password: good00bye
  maximumPoolSize: 10
  minimumIdle: 2
  connectionTimeout: 30000